from pymongo import MongoClient
import os
from dotenv import load_dotenv
from datetime import datetime

load_dotenv()

MONGO_URI = os.getenv("MONGO_URI", "mongodb://localhost:27017")
DB_NAME = "MindRiseDB"
COLLECTION_NAME = "user_videos"

def initialize_db():
    try:
        client = MongoClient(MONGO_URI)
        db = client[DB_NAME]
        collection = db[COLLECTION_NAME]
        
        # Sample document mapping the requested fields
        sample_record = {
            "user_id": "6988acee24f625f056f16116", # Example User ID (Madhav)
            "video_url": "https://res.cloudinary.com/dbcucwjrw/video/upload/v1770816572/videoplayback_wttlew.mp4",
            "caption": "A beautiful morning for mindfulness. #peace #growth",
            "status": "Pending", # Options: Pending / Approved / Rejected
            "created_at": datetime.utcnow() # Current timestamp
        }
        
        # Note: video_id is auto-generated by MongoDB as '_id'
        
        result = collection.insert_one(sample_record)
        print(f"Successfully initialized {DB_NAME}.{COLLECTION_NAME}")
        print(f"Inserted sample record ID: {result.inserted_id}")
        print("\nSchema Implemented:")
        print(f" - _id (video_id): {result.inserted_id} (Auto-generated)")
        print(f" - user_id: {sample_record['user_id']}")
        print(f" - video_url: {sample_record['video_url']}")
        print(f" - caption: {sample_record['caption']}")
        print(f" - status: {sample_record['status']}")
        print(f" - created_at: {sample_record['created_at']}")
        
    except Exception as e:
        print(f"Error during initialization: {e}")

if __name__ == "__main__":
    initialize_db()
